all: controla suma solo_pares suma_pares

controla: controla.c
	gcc -o controla controla.c

suma: suma.c
	gcc -o suma suma.c

solo_pares: solo_pares.c
	gcc -o solo_pares solo_pares.c

suma_pares: suma_pares.c
	gcc -o suma_pares suma_pares.c

clean:
	rm controla