all:suma_enters generadornums compta_linies generadornumsascii

suma_enters: suma_enters.c
	gcc -o suma_enters suma_enters.c

compta_linies: compta_linies.c
	gcc -o compta_linies compta_linies.c

generadornums: generadornums.c
	gcc -o generadornums generadornums.c

generadornumsascii: generadornumsascii.c
	gcc -o generadornumsascii generadornumsascii.c

clean:
	rm -f suma_enters generadornums generadornumsascii compta_linies

