all:add_integers generadornums count_lines generadornumsascii

add_integers: add_integers.c
	gcc -o add_integers add_integers.c

count_lines: count_lines.c
	gcc -o count_lines count_lines.c

generadornums: generadornums.c
	gcc -o generadornums generadornums.c

generadornumsascii: generadornumsascii.c
	gcc -o generadornumsascii generadornumsascii.c

clean:
	rm -f add_integers generadornums generadornumsascii count_lines

