all: hermano signal hermano2

hermano: hermano.c
	gcc -o hermano hermano.c
signal: signal.c
	gcc -o signal signal.c
hermano2: hermano2.c
	gcc -o hermano2 hermano2.c

clean:
	rm hermano signal hermano2