all: listaParametros punteros words

listaParametros: listaParametros.c
	gcc -o listaParametros listaParametros.c
punteros:
	gcc -o punteros punteros.c
words:
	gcc -o words words.c

clean:
	rm listaParametros
	rm punteros
	rm words